FORMAT: 1A
HOST: https://xlb-user-data.apiblueprint.org/

# XLBUserBase

XLB is a simple API allowing consumers to get users and create them.

## Users Collection [/users]

### List All Users [GET]

+ Response 200 (application/json)

        {
            "users": [ 
                {
                        "id": "1",
                        "name": "Devee",
                        "username": "dev1",
                        "password": "admin",
                        "team": []
                }, 
                {
                        "id": "2",
                        "name": "Dev Devv",
                        "username": "dev2",
                        "password": "admin",
                        "team": []
                }
            ]
        }

### Register User [POST]

You may create a user using this action. It takes a username and password.

+ Request (application/json)

        data%5BXLBUserBase%5D%5Bid%5D=qq&data%5BXLBUserBase%5D%5Bname%5Dqq&data%5BXLBUserBase%5D%5Busername%5Dqq&data%5BXLBUserBase%5D%5Bpassword%5D=0

+ Response 201 (application/json)

    + Headers

            Location: /users

    + Body

            {
                "user": {
                    "id": 1,
                    "name": "Devee",
                    "team": []
                }
            }